{{- if and .Values.postgres.enabled .Values.postgres.url (not .Values.postgres.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "overclockdb.postgresSecretName" . }}
  labels:
    {{- include "overclockdb.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-url: {{ .Values.postgres.url | b64enc | quote }}
{{- end }}
